server:
  port: 8080

spring:
  application:
    name:classdemo

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/project1?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapping/*.xml
  type-aliases-package: com.nsw.dirs