server:
  port: 8080

spring:
  application:
    name:classdemo
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/project1?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    mvc:
     date-format: yyyy-MM-dd
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
  mail:
    host: smtp.qq.com
    username: 1742314729@qq.com
    password: wdayixqrmhjfbhif
    properties:
      mail:
        smtp:
          ssl:
            enable: true
mybatis:
  mapper-locations: classpath*:mapping/*.xml
  type-aliases-package: com.nsw.dirs
cbs:
  imagesPath: D:/zhaopian/