server:
  port: 8080
spring:
  application:
    name:nsw
  datasource:
    username: root
    password: 2001wqz
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
mybatis:
  mapper-locations: classpath*:mapping/*.xml
  type-aliases-package: com.nsw.dirs
cbs:
  imagesPath: D:/zhaopian/
